# Generated by Django 3.1.5 on 2021-02-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_realm', '0008_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='charisma_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trait',
            name='constitution_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trait',
            name='dexterity_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trait',
            name='intelligence_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trait',
            name='strength_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trait',
            name='wisdom_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
